//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLootHeavies.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoLootHeavies.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance-based teleportation is now OFF..
        /// </summary>
        public static string DistTeleOff {
            get {
                return ResourceManager.GetString("DistTeleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance-based teleportation is now ON..
        /// </summary>
        public static string DistTeleOn {
            get {
                return ResourceManager.GetString("DistTeleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump ore here!.
        /// </summary>
        public static string DumpOre {
            get {
                return ResourceManager.GetString("DumpOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump stone &amp; marble here!.
        /// </summary>
        public static string DumpStone {
            get {
                return ResourceManager.GetString("DumpStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump timber here!.
        /// </summary>
        public static string DumpTimber {
            get {
                return ResourceManager.GetString("DumpTimber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with the magic of teleporting resources - please let me know. A log was saved in the mod directory..
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dang, no ore stockpiles in range....
        /// </summary>
        public static string NoOreInRange {
            get {
                return ResourceManager.GetString("NoOreInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t do that, I have no ore storage left!.
        /// </summary>
        public static string NoOreStorageLeft {
            get {
                return ResourceManager.GetString("NoOreStorageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dang, no stone stockpiles in range....
        /// </summary>
        public static string NoStoneInRange {
            get {
                return ResourceManager.GetString("NoStoneInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t do that, I have no stone storage left!.
        /// </summary>
        public static string NoStoneStorageLeft {
            get {
                return ResourceManager.GetString("NoStoneStorageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dang, no timber stockpiles in range....
        /// </summary>
        public static string NoTimberInRange {
            get {
                return ResourceManager.GetString("NoTimberInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t do that, I have no timber storage left!.
        /// </summary>
        public static string NoTimberStorageLeft {
            get {
                return ResourceManager.GetString("NoTimberStorageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phew...ore storage is now full!.
        /// </summary>
        public static string OreFull {
            get {
                return ResourceManager.GetString("OreFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phew...stone storage is now full!.
        /// </summary>
        public static string StoneFull {
            get {
                return ResourceManager.GetString("StoneFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleportation is now OFF..
        /// </summary>
        public static string TeleOff {
            get {
                return ResourceManager.GetString("TeleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleportation is now ON..
        /// </summary>
        public static string TeleOn {
            get {
                return ResourceManager.GetString("TeleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phew...timber storage is now full!.
        /// </summary>
        public static string TimberFull {
            get {
                return ResourceManager.GetString("TimberFull", resourceCulture);
            }
        }
    }
}
